name: ci

on:
  push:
    branches: main
    #paths:
    #  - 'Development/php7.4-apache/Dockerfile'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: egahmad
          password: 7682894b-eb7e-4fb6-a951-2ec2803346d8
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: 'Development/php7.4-apache/'
          file: ./Dockerfile 
          push: true
          tags: egahmad/php7.4-apache-development.yml:latest
          #build-args: |
          #  arg1=value1
          #  arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
